#!/usr/bin/env python3
"""MCP 工具清单生成脚本 / MCP Tool List Generator.

从 phone_pilot/mcp/server.py 提取工具名，与 tool_contracts.py 契约表交叉验证，
生成 docs/verification/mcp_tool_list_generated.md。

Extracts tool names from server.py, cross-validates with tool_contracts,
generates mcp_tool_list_generated.md.

运行约定 / Run conventions:
- 工作目录 / Working dir: 默认项目根 / project root by default
  可通过 --cwd 或 PHONE_PILOT_PROJECT_ROOT 指定 / Override with --cwd or env
- 前置条件 / Prerequisites: 已安装 phone_pilot (pip install -e .)、Python >= 3.10
- 推荐命令 / Recommended: python scripts/generate_mcp_tool_list.py
- 输出目录若不存在会自动创建 / Output dir created if missing
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path


def get_project_root(cwd: str) -> Path:
    """解析项目根目录。Resolve project root directory."""
    root = Path(cwd).resolve()
    marker = root / "phone_pilot" / "mcp" / "server.py"
    if not marker.is_file():
        raise SystemExit(f"ERROR: project root not found (missing {marker})")
    return root


def extract_tool_names_from_server(server_path: Path) -> list[str]:
    """从 server.py 扫描 async def phone_*( 提取工具名。
    Scan server.py for async def phone_* to extract tool names."""
    content = server_path.read_text(encoding="utf-8")
    names = re.findall(r"^async def (phone_\w+)\s*\(", content, re.MULTILINE)
    return names


def load_contracts(project_root: Path) -> dict:
    """加载契约表。Load contract table from tool_contracts."""
    # 确保项目根在 sys.path 以便导入 phone_pilot
    # Ensure project root in sys.path for importing phone_pilot
    root_str = str(project_root)
    if root_str not in sys.path:
        sys.path.insert(0, root_str)

    from phone_pilot.mcp.tool_contracts import get_all_contracts

    return get_all_contracts()


def cross_validate(
    server_tools: list[str], contracts: dict
) -> tuple[list[str], list[str]]:
    """交叉验证：返回 (server有契约无→报错列表, 契约有server无→警告列表)。
    Cross-validate: return (in_server_not_contract, in_contract_not_server)."""
    server_set = set(server_tools)
    contract_set = set(contracts.keys())

    in_server_not_contract = sorted(server_set - contract_set)
    in_contract_not_server = sorted(contract_set - server_set)

    return in_server_not_contract, in_contract_not_server


def generate_markdown(
    contracts: dict, generated_at: str, out_path: Path
) -> None:
    """生成 Markdown 表格文件。Generate Markdown table file."""
    lines = [
        "# MCP 工具清单（自动生成）/ MCP Tool List (auto-generated)",
        "",
        "> 由 scripts/generate_mcp_tool_list.py 自动生成，请勿手改。",
        "> Auto-generated by scripts/generate_mcp_tool_list.py, do not edit manually.",
        "> ",
        f"> 生成时间 / Generated at: {generated_at}",
        "",
        "| # | 工具名 / Tool Name | 分类 / Category | 成功必含键 / OK Required Keys | 失败必含键 / Error Required Keys |",
        "|---|---|---|---|---|",
    ]

    # 按 tool_contracts 注册顺序（dict 保持插入顺序）
    # Order by tool_contracts registration order (dict preserves insertion order)
    for i, (tool_name, c) in enumerate(contracts.items(), start=1):
        ok_keys = ", ".join(c.required_keys_when_ok)
        err_keys = ", ".join(c.required_keys_when_error)
        lines.append(f"| {i} | {tool_name} | {c.category} | {ok_keys} | {err_keys} |")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate MCP tool list from server.py and tool_contracts.py"
    )
    parser.add_argument(
        "--cwd",
        type=str,
        help="Override working directory (project root)",
    )
    parser.add_argument(
        "--output",
        type=str,
        help="自定义输出路径 / Custom output file path (default: docs/verification/mcp_tool_list_generated.md)",
    )
    args = parser.parse_args()

    # 工作目录：--cwd > PHONE_PILOT_PROJECT_ROOT > 当前目录
    # Working dir: --cwd > PHONE_PILOT_PROJECT_ROOT > current dir
    cwd = args.cwd or os.environ.get("PHONE_PILOT_PROJECT_ROOT") or os.getcwd()
    project_root = get_project_root(cwd)

    server_path = project_root / "phone_pilot" / "mcp" / "server.py"
    server_tools = extract_tool_names_from_server(server_path)
    contracts = load_contracts(project_root)

    in_server_not_contract, in_contract_not_server = cross_validate(
        server_tools, contracts
    )

    # server 有但契约无 → 报错并退出
    # In server but not in contracts → error and exit
    if in_server_not_contract:
        print("ERROR: Tools in server.py but not in tool_contracts:", file=sys.stderr)
        for t in in_server_not_contract:
            print(f"  - {t}", file=sys.stderr)
        sys.exit(1)

    # 契约有但 server 无 → 警告
    # In contracts but not in server → warning
    if in_contract_not_server:
        print(
            "WARNING: Tools in tool_contracts but not in server.py:",
            file=sys.stderr,
        )
        for t in in_contract_not_server:
            print(f"  - {t}", file=sys.stderr)

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    # 输出路径：--output > 默认 docs/verification/mcp_tool_list_generated.md
    # Output path: --output > default docs/verification/mcp_tool_list_generated.md
    if args.output:
        out_path = Path(args.output).resolve()
    else:
        out_path = project_root / "docs" / "verification" / "mcp_tool_list_generated.md"
    generate_markdown(contracts, generated_at, out_path)

    print(f"Generated: {out_path} ({len(contracts)} tools)")


if __name__ == "__main__":
    main()
